# Generated by Django 5.2.1 on 2025-05-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('value', models.CharField(max_length=100, verbose_name='Valor')),
                ('transaction_date', models.DateField(verbose_name='Data da transação')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de edição')),
            ],
        ),
    ]
